apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: product-service-eventing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: docker.io/knativedemo/product-service-eventing