apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order-service-eventing
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: docker.io/knativedemo/order-service-eventing
          env: 
           - name: TARGET
             value: "order-service-2"