spring.application.name: product-service
spring.cloud.function.web.path: /products
spring.kafka.bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092
#spring.cloud.function.definition: block;blockBT
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:product
    username: sa
    password: password
    driverClassName: org.h2.Driver  
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
