spring.application.name: customer-service
spring.cloud.function.web.path: /customers
spring.kafka.bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092
#spring.cloud.function.definition: blockAmount;blockAmountBT

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: password
    driverClassName: org.h2.Driver  
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop