spring.application.name: order-service
spring.cloud.function.web.path: /orders
spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
