spring.application.name: customer-service
spring.cloud.function.web.path: /customers
spring.cloud.function.definition: blockAmount;

spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
