FROM maven:3.8.3-openjdk-17 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean install


FROM openjdk:17-alpin
COPY --from=build /usr/src/app/target/*.jar /usr/app/order-service.jar
# ARG JAR_FILE=/usr/app/*.jar
# COPY ${JAR_FILE} order-service.jar
ENTRYPOINT ["java","-jar","/usr/app/order-service.jar"]
