apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: order-event-source-bt
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - create-order
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      