apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: order-subscriber
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: order-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-service-eventing
    uri: /orders/confirmOrderCS