apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: order-event-source-cs
spec:
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - purchase-order
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: default
      